server:
  port: 9998

cookies:
  rail_expiration: "1564951122019"
  rail_deviceid: "pV3ZJyEkK5XFd4flmzV_pDSg8i3oW5cXJUTHWd1LN54qePu_1b37mCt6SfJDH_lSlD92Fya9Uvhk_rQxVoDJ7JUSikgZSb7fxgKE1YfgmotDk_IuMeWOOSlFy4tFWx6ARXpbrOEZxONDbiL8F6hdS40AQ9Jt7rDl"
config:
  host: "kyfw.12306.cn"
  base_url: "https://kyfw.12306.cn"
  queryTicketSellpTime: 1
  pythonPath: "python"
  logdevicePath: "classpath:logdevice.js"

api:
  station: "${config.base_url}/otn/resources/js/framework/station_name.js?station_version=1.9098"
  getJs: "${config.base_url}/otn/HttpZF/GetJS"
  logdevice: "${config.base_url}/otn/HttpZF/logdevice?algID=%s&timestamp=%s"
  init: "${config.base_url}/otn/leftTicket/init"
  leftTicket: "${config.base_url}/otn/leftTicket/query?leftTicketDTO.train_date=%s&leftTicketDTO.from_station=%s&leftTicketDTO.to_station=%s&purpose_codes=ADULT"
  loginConfig: "${config.base_url}/otn/login/conf"
  passengers: "${config.base_url}/otn/passengers/query"
  captchaImage: "${config.base_url}/passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&_=%s"
  uamtkStatic: "${config.base_url}/passport/web/auth/uamtk-static?appid=otn"
  login: "${config.base_url}/passport/web/login"
  captchaCheck: "${config.base_url}/passport/captcha/captcha-check?answer=%s&rand=sjrand&login_site=E&_=%s"
  uamtk: "${config.base_url}/passport/web/auth/uamtk"
  uamauthclient: "${config.base_url}/otn/uamauthclient"
  checkUser: "${config.base_url}/otn/login/checkUser"
  submitOrderRequest: "${config.base_url}/otn/leftTicket/submitOrderRequest"
  initDc: "${config.base_url}/otn/confirmPassenger/initDc"
  getPassengerDTOs: "${config.base_url}/otn/confirmPassenger/getPassengerDTOs"
  checkOrderInfo: "${config.base_url}/otn/confirmPassenger/checkOrderInfo"
  checkRandCodeAnsyn: "${config.base_url}/otn/passcodeNew/checkRandCodeAnsy"
  getQueueCount: "${config.base_url}/otn/confirmPassenger/getQueueCount"
  confirmSingleForQueue: "${config.base_url}/otn/confirmPassenger/confirmSingleForQueue"
  queryOrderWaitTime: "${config.base_url}/otn/confirmPassenger/queryOrderWaitTime?random=%s&tourFlag=dc&_json_att=&REPEAT_SUBMIT_TOKEN=%s"
  notice: "dysmsapi.aliyuncs.com"

spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:sqlite::resource:db/ticket.db"
    driver-class-name: org.sqlite.JDBC
  profiles:
    include:
      - user
      - sms

swagger:
  enabled: true
  title: 12306抢票系统
  description: 12306抢票系统
  webBasePackage: com.qianxunclub.ticket.controller
  author: 千寻啊千寻
  url: qianxunclub.com
  email: qianxunclub@qq.com

logging:
  level:
    com.qianxunclub: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr([%50t]){faint} %clr(:){faint} %m%n%wEx"
